from pg_configurator.conf_profiles.profile_1c import alg_set_1c
from pg_configurator.conf_profiles.ext_perf import ext_alg_set
from pg_configurator.conf_profiles.profile_platform_common import platform_common_alg_set
from pg_configurator.conf_profiles.profile_platform_perf import platform_perf_alg_set
